services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - payment-network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ezycollect-payment?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - payment-network
    environment:
      MYSQL_DATABASE: ezycollect-payment
      MYSQL_USER: ezyuser
      MYSQL_PASSWORD: 12345678()
      MYSQL_ROOT_PASSWORD: 12345678()
networks:
  payment-network: